In [1]:
from utils import simulator as sml

In [2]:
simulador = sml.Simulator(4)

In [3]:
simulador.nEnvironment

4

In [4]:
simulador.matrixA

array([[0.78543779, 0.33388617, 0.35627176, 0.78447878],
       [0.35682403, 0.43087717, 0.83991488, 0.94838577],
       [0.50861909, 0.51186652, 0.60707806, 0.29830619],
       [0.21522114, 0.59851433, 0.02370551, 0.07340124]])

In [5]:
simulador.matrixB

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
simulador.matrixP

array([[-4.64365446, -0.42445971, -5.33479009, -8.03446718],
       [-5.83345776, -4.11349727, -8.71729375, -4.44855063],
       [-7.85819363, -1.66915682, -6.12007322, -9.91531733],
       [-8.729783  , -1.27201825, -9.35124761, -5.45366246]])

In [7]:
simulador.arrayU

array([0., 0., 0., 0.])

In [8]:
simulador.arrayT

array([22, 23, 27, 15])

In [9]:
simulador.Ttarget

array([20, 20, 20, 20])

In [10]:
type(simulador.matrixB)

numpy.ndarray

In [11]:
simulador.post_status_nEnvironment()

array([22, 23, 27, 15])

In [12]:
simulador.update_memory_list()

In [13]:
simulador.post_status_nEnvironment()

array([46.34553252, 54.66379198, 43.82825053, 20.24176197])

In [14]:
simulador.memory_list

[array([22, 23, 27, 15]),
 array([46.34553252, 54.66379198, 43.82825053, 20.24176197])]

In [15]:
import numpy as np

In [16]:
np.all(simulador.arrayT == simulador.Ttarget)

False

In [17]:
sml2 = sml.Simulator(4)
n = 0
T, Ttarget, U = sml2.arrayT, sml2.Ttarget, sml2.arrayU

In [18]:
Ttarget

array([20, 20, 20, 20])

In [19]:
T

array([18, 29, 27, 30])

In [20]:
U

array([0., 0., 0., 0.])

In [21]:
T = sml2.update_arrayT()

In [22]:
T

array([35.21519336, 78.23657072, 65.55283373, 53.4150841 ])

In [23]:
U = sml2.update_arrayU()

In [24]:
print(U)

[770. 432. 991. 405.]


In [25]:
simulador2 = sml.Simulator(4)
n = 0
T, Ttarget, U = simulador2.arrayT, simulador2.Ttarget, simulador2.arrayU
while np.all(T == Ttarget) != True:
    if n>1000:
        print(T)
        print()
        print(U)
        break
    T, U = simulador2.update_arrayT(), simulador2.update_arrayU()
    
    print(f"Atualização: {n+1} ---- {U} --- {T}")
    n += 1



AttributeError: module 'utils.simulator' has no attribute 'arrayT'

In [ ]:
print(sml.arrayT, sml.Ttarget, sml.arrayU)

[nan nan nan nan] [20 20 20 20] [nan nan nan nan]
